name: 👮‍♂️ Sanity checks

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 24
        go_version:
          - 1.25

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node_version }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go_version }}
          cache: False

      - name: Install `shfmt`
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - name: Run Prettier
        run: npx prettier -c '**/*.{md,yml,yaml}'

      - name: Run `shfmt`
        run: shfmt -d safe_hashes.sh install.sh

  codespell:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          skip: ./.git

  validate-links:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        ruby_version:
          - 3.4

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Install awesome_bot
        run: gem install awesome_bot

      - name: Validate URLs
        run: awesome_bot ./*.md ./*.sh --allow-dupe --request-delay 0.4 --white-list https://opensea.io,https://linux.die.net/man/1/tput,https://etherscan.io
